name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build-apk:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Build APK with Buildozer
        uses: digreatbrian/buildozer-action@v2
        with:
          command: buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: zkteco-time-tool-apk
          path: bin/*.apk
